<?php

function formatarLinhaDigitavel($linhaDigitavel) {
       // Remover pontos e espaços em branco da linha digitável
    $linhaDigitavel = str_replace(['.', ' '], '', $linhaDigitavel);

    $blocos = array(
        substr($linhaDigitavel, 0, 5) . '.' . substr($linhaDigitavel, 5, 5),
        substr($linhaDigitavel, 10, 5) . '.' . substr($linhaDigitavel, 15, 6),
        substr($linhaDigitavel, 21, 5) . '.' . substr($linhaDigitavel, 26, 6),
        substr($linhaDigitavel, 32, 1),
        substr($linhaDigitavel, 33)
    );

    return implode(' ', $blocos);
}

function consultarBoleto($linha_digitavel_formatada) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://www.f2b.com.br/app/v1/pagamentos/boleto');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
        "linha_digitavel" => $linha_digitavel_formatada,
        "etapa_validacao" => 1
    ]));

    // HEADERS: GATE-TOKEN NAO PRECISA;
    $headers = array();
    $headers[] = 'Host: www.f2b.com.br';
    $headers[] = 'Accept: application/json, text/plain, */*';
    $headers[] = 'Authorization: Basic cGRCZURhZC1mbWlwczdtYS1ncGxwLTZsYWwtdnFtcHA0dHA=';
    $headers[] = 'Sec-Fetch-Site: cross-site';
    $headers[] = 'Mobile-Uuid: A80CEB57-4F12-409B-8E5F-B36D2D833127';
    $headers[] = 'Mobile_uuid: A80CEB57-4F12-409B-8E5F-B36D2D833127';
    $headers[] = 'Accept-Language: pt-BR,pt;q=0.9';
    $headers[] = 'Sec-Fetch-Mode: cors';
    $headers[] = 'Origin: null';
    $headers[] = 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148';
    $headers[] = 'Content-Length: ' . strlen(json_encode([
        "linha_digitavel" => $linha_digitavel_formatada,
        "etapa_validacao" => 1
    ]));
    $headers[] = 'Connection: keep-alive';
    $headers[] = 'Sec-Fetch-Dest: empty';
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    echo "$result";
	return $result;
}

function revalidarSessao() {
				// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
			$ch = curl_init();

			curl_setopt($ch, CURLOPT_URL, 'https://www.f2b.com.br/app/v1/cliente/login');
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"login_email\":\"marciomoreirag69@gmail.com\",\"password\":\"240735072407\",\"isFingerprint\":\"N\",\"gps_location\":\"undefined,undefined\",\"appVersion\":\"1.1.20\",\"appVersionInt\":\"1001020\"}");

			$headers = array();
			$headers[] = 'Host: www.f2b.com.br';
			$headers[] = 'Accept: application/json, text/plain, */*';
			$headers[] = 'Authorization: Basic cGRCZURhZC1mbWlwczdtYS1ncGxwLTZsYWwtdnFtcHA0dHA=';
			$headers[] = 'Sec-Fetch-Site: cross-site';
			$headers[] = 'Mobile-Uuid: A80CEB57-4F12-409B-8E5F-B36D2D833127';
			$headers[] = 'Mobile_uuid: A80CEB57-4F12-409B-8E5F-B36D2D833127';
			$headers[] = 'Accept-Language: pt-BR,pt;q=0.9';
			$headers[] = 'Sec-Fetch-Mode: cors';
			$headers[] = 'Gate-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBODBDRUI1Ny00RjEyLTQwOUItOEU1Ri1CMzZEMkQ4MzMxMjciLCJzdWIiOiJRVGd3UTBWQ05UY3RORVl4TWkwME1EbENMVGhGTlVZdFFqTTJSREpFT0RNek1USTMiLCJleHAiOjE2OTE0OTg5ODh9.WmJjADqvsDuvxyTgmmoUvLR53HglstRhy5p7wObJlwQ';
			$headers[] = 'Origin: null';
			$headers[] = 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148';
			$headers[] = 'Content-Length: 175';
			$headers[] = 'Connection: keep-alive';
			$headers[] = 'Sec-Fetch-Dest: empty';
			$headers[] = 'Content-Type: application/json';
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

			$result2 = curl_exec($ch);
			if (curl_errno($ch)) {
				echo 'Error:' . curl_error($ch);
			}
			curl_close($ch);

			//echo"$result2";
			 return $result2;
}

// Verificar se o formulário foi submetido
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    // Obter a linha digitável do boleto enviada pelo formulário
    $linha_digitavel = $_POST['linha_digitavel'];
    echo $linha_digitavel . "<br>";

    // Formatar a linha digitável
    $linha_digitavel_formatada = formatarLinhaDigitavel($linha_digitavel);
    echo "linha: $linha_digitavel_formatada"; exit;

    // Consultar o boleto e obter a resposta
    $result = consultarBoleto($linha_digitavel_formatada);

    // Verificar se a resposta contém a palavra "Sessão expirada"
    if (strpos($result, 'expirada') !== false) {
        // Se a sessão expirou, revalidar a sessão
        $result2 = revalidarSessao();

        // Tentar a consulta novamente
        $result = consultarBoleto($linha_digitavel_formatada);
    }

    // Imprimir a resposta apropriada
    if (strpos($result, 'beneficiario') !== false) {
        echo "NAO PAGO - Em Aberto";
    } elseif (strpos($result, 'baixado') !== false) {
        echo "PAGO - Baixado";
    } elseif (strpos($result, 'liquidado') !== false) {
        echo "PAGO - Liquidado";
    } elseif (strpos($result, 'duplicidade') !== false) {
        echo "PAGO - Duplicidade";
    } elseif (strpos($result, 'inapto') !== false) {
        echo "ERRO - Benificiario INAPTO";
    }  else {
        echo "Status desconhecido";
    }
}
?>
